---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-bigip-ctlr
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr
      labels:
        app: k8s-bigip-ctlr
    spec:
      # Name of the Service Account bound to a Cluster Role with the required
      # permissions
      serviceAccountName: bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          # replace the version as needed
          image: "f5networks/k8s-bigip-ctlr:1.5"
          env:
            - name: BIGIP_USERNAME
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: username
            - name: BIGIP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bigip-login
                  key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
            "--bigip-username=$(BIGIP_USERNAME)",
            "--bigip-password=$(BIGIP_PASSWORD)",
            "--bigip-url={{ bigip_url }}",
            "--bigip-partition={{ bigip_partition }}",
            "--pool-member-type=cluster",
            "--manage-routes=true",
            "--route-vserver-addr={{ route_vserver_addr }}",
            "--log-level={{ log_level }}",
            "--openshift-sdn-name={{ openshift_sdn_name }}",
            "--route-http-vserver=VIP_OCP_DEV_HTTP",
            "--route-https-vserver=VIP_OCP_DEV_HTTPS",
            "--default-server-ssl={{ default_server_ssl }}",
            "--route-label={{ route_label }}",
            ]
      imagePullSecrets:
        # Secret that gives access to a private Docker registry
        - name: f5-docker-images
        # Secret containing the BIG-IP system login credentials
        - name: bigip-login
...